In [ ]:
#consigna 1
import numpy as np
def serie(a, b, c):
  array = np.random.randint(a, b+1, size = c)
  print(array)
  mediana = np.median(array)
  print("La mediana es ", mediana)

serie(2,50,20)

serie(10,20,10)

serie(5,25,3)

[14 40 46 23  5  7 49 42 17  6 44 39 17 26 26 41 18  6 29 44]
La mediana es  26.0
[15 13 20 14 18 12 11 16 13 20]
La mediana es  14.5
[11 20 19]
La mediana es  19.0


In [ ]:
#consigna 2
print("Factorial")

import numpy as np
def factorial(n):
  print("El factorial de", n, "es", int(np.prod(range(1,n+1))))

factorial(4)

factorial(0)

print("Suma de serie")
import numpy as np
def serie(a,b,c):
  if b<a:
    print("Error, introduzca un numero b mayor que ", a)
  else:
    serie = np.arange(a, b+1, c)
    suma = serie.sum()
    print(serie)
    print(suma)

serie(5,0,2)

serie(2,10,1)

Factorial
El factorial de 4 es 24
El factorial de 0 es 1
Suma de serie
Error, introduzca un numero b mayor que  5
[ 2  3  4  5  6  7  8  9 10]
54


In [ ]:
#conexion  a google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#consigna 3
import pandas as pd
import numpy as np
documento = pd.read_excel('/content/drive/MyDrive/Salarios Openqube.xlsx')
data = (documento['Salario mensual NETO (en tu moneda local)'])
serie = pd.Series(data)
serie.fillna(0, inplace=True)
mediana = np.median(serie)
media = serie.mean()
print("""
    Media: %d
    Mediana: %d
""" % (media,mediana))


    Media: 18656271
    Mediana: 75000

